# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: auto
        threshold: 1%
        informational: false

  range: 50..100

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "spec/**/*"
  - "test/**/*"
  - "config/**/*"
  - "db/**/*"
  - "vendor/**/*"
  - "node_modules/**/*"
